DATN/Areas/Admin/Controllers/DiemController.cs
using DATN.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DATN.Areas.Admin.Controllers
{
    public class DiemController : Controller
    {
		DataTVUDataContext db = new DataTVUDataContext();
        // GET: Admin/Diem
        public ActionResult Index()
        {
			ViewBag.Diem = db.DIEMs.Select(x => new DanhSachDiem { MaMon = x.MON.Ma_Mon, MaSV = x.SINHVIEN.Ma_SV,Lop = x.SINHVIEN.LOP.Ma_Lop, TenMon = x.MON.Ten_Mon, HocKi = x.MON.HOCKI.Ma_HK, TinChi = x.MON.So_TC, ThiL1 = x.Thi_L1, ThiL2 = x.Thi_L2, ThiL3 = x.Thi_L3, TK10 = x.TK10, TKCH = x.TKCH, KQ1 = x.KQ1, KQ = x.KQ, GhiChu = x.Ghi_Chu }).ToList();
			return View();
        }
    }
}

DATN/Areas/Admin/Views/Shared/_Layout.cshtml
@{
	if (Session["role"] == null)
	{
		Response.Redirect("~/admin/AdminLogin",false);
	}
}

<!DOCTYPE html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Hệ thống gợi ý môn học - Admin</title>
	<!-- plugins:css -->
	<link rel="stylesheet" href="~/Assets/vendors/iconfonts/mdi/css/materialdesignicons.min.css">
	<link rel="stylesheet" href="~/Assets/vendors/css/vendor.bundle.base.css">
	<!-- endinject -->
	<!-- inject:css -->
	<link rel="stylesheet" href="~/Assets/css/style.css">

	<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
	<link href="~/Assets/datatable/Responsive-2.2.2/css/responsive.bootstrap.min.css" rel="stylesheet" />
	<link href="~/Assets/datatable/FixedHeader-3.1.4/css/fixedHeader.bootstrap.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
	<!-- endinject -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
	<link href="~/Assets/css/loading.css" rel="stylesheet" />
	<link rel="shortcut icon" href="~/Assets/images/seo.png" />
	<link href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css" />
	@RenderSection("ClientCss", false)


</head>


<body onunload="loader()" onload="loader()">
	<div id="loading">
		<div class="loader">
			<span></span>
			<span></span>
			<span></span>
			<span></span>
		</div>
	</div>
	<div class="container-scroller">
		<!-- partial:partials/_navbar.html -->
		<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
			<div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
				<a class="navbar-brand brand-logo" href="@Url.Action("index","home")"><img src="~/Assets/images/isearch.png" alt="logo" /></a>

			</div>
			<div class="navbar-menu-wrapper d-flex align-items-stretch">
				<div class="search-field d-none d-md-block">
					<form class="d-flex align-items-center h-100" action="#">
						<div class="input-group">
							<div class="input-group-prepend bg-transparent">
								<i class="input-group-text border-0 mdi mdi-magnify"></i>
							</div>
							<input type="text" class="form-control bg-transparent border-0" id="search_input" placeholder="Search">
						</div>
					</form>
				</div>
				<ul class="navbar-nav navbar-nav-right">
					<li class="nav-item nav-profile dropdown">
						<a class="nav-link dropdown-toggle" id="profileDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
							<div class="nav-profile-img">
								<img src="~/Assets/images/logotvu.png" alt="image">
								<span class="availability-status online"></span>
							</div>
							<div class="nav-profile-text">
								<p class="mb-1 text-black">@Session["email"]</p>
							</div>
						</a>
						<div class="dropdown-menu navbar-dropdown" aria-labelledby="profileDropdown">
							@*<a class="dropdown-item" href="#">
									<i class="mdi mdi-cached mr-2 text-success"></i>
									Activity Log
								</a>*@
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="@Url.Action("Logout","AdminLogin")">
								<i class="mdi mdi-logout mr-2 text-primary"></i>
								Signout
							</a>
						</div>
					</li>

					<li class="nav-item d-none d-lg-block full-screen-link">
						<a class="nav-link">
							<i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
						</a>
					</li>

					<li class="nav-item nav-settings d-none d-lg-block">
						<a class="nav-link" href="#">
							<i class="mdi mdi-format-line-spacing"></i>
						</a>
					</li>
				</ul>
				<button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
					<span class="mdi mdi-menu"></span>
				</button>
			</div>
		</nav>
		<!-- partial -->
		<div class="container-fluid page-body-wrapper">
			<!-- partial:partials/_sidebar.html -->
			<nav class="sidebar sidebar-offcanvas" id="sidebar">
				<ul class="nav">
					<li class="nav-item nav-profile">
						<a href="#" class="nav-link">
							<div class="nav-profile-image">
								<img src="~/Assets/images/logotvu.png" alt="profile">
								<span class="login-status online"></span> <!--change to offline or busy as needed-->
							</div>
							<div class="nav-profile-text d-flex flex-column">
								<span class="font-weight-bold mb-2">@Session["name"]</span>
								<span class="text-secondary text-small">Tra Cứu</span>
							</div>
							<i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
						</a>
					</li>

					<li class="nav-item">
						<a class="nav-link" href="@Url.Action("Index","Home")">
							<span class="menu-title">Home</span>
							<i class="mdi mdi-home menu-icon"></i>
						</a>
					</li>

					<li class="nav-item">
						<a class="nav-link" href="@Url.Action("Index","CTDT")">
							<span class="menu-title">Chương trình đào tạo</span>
							<i class="mdi mdi-android-studio menu-icon"></i>
						</a>
					</li>

					<li class="nav-item">
						<a class="nav-link" href="@Url.Action("Index","Lop")">
							<span class="menu-title">Lớp</span>
							<i class="mdi mdi-format-list-bulleted menu-icon"></i>
						</a>
					</li>

					<li class="nav-item">
						<a class="nav-link" href="@Url.Action("Index","Diem")">
							<span class="menu-title">Danh sách điểm</span>
							<i class="mdi mdi-calendar-multiple menu-icon"></i>
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="@Url.Action("Index","Lich")">
							<span class="menu-title">Lịch Môn</span>
							<i class="mdi mdi-calendar-multiple menu-icon"></i>
						</a>
					</li>

					<li class="nav-item sidebar-actions">
						<span class="nav-link">
							<div class="border-bottom"></div>
							<button class="btn btn-block btn-lg btn-gradient-primary mt-4 btn-capnhaplichmon" onclick="showDialogLich()">Cập nhật lịch môn</button>
						</span>
					</li>


				</ul>
			</nav>
			<!-- partial -->
			<div class="main-panel">
				<div class="content-wrapper">
					@RenderBody()
				</div>
			</div>
		</div>

		<!-- page-body-wrapper ends -->

	</div>

	@*Modal upload lich*@
	<div class="card modal" id="model-lich">
		<div class="card-body">
			@using (Html.BeginForm("Upload", "Lich", FormMethod.Post, new { enctype = "multipart/form-data" }))
			{
				@Html.AntiForgeryToken()
				<div class="row">
					<div class="col-md-12">
						<div class="form-group row">
							<label class="col-sm-4 col-form-label"> File Excel </label>
							<div class="col-sm-8">
								<input type="file" class="file-upload-default file-click" name="excelfilelich" />
								<div class="input-group col-xs-12">
									<input type="text" class="form-control file-upload-info name-input" disabled="" placeholder="Upload File">
									<span class="input-group-append">
										<button class="file-upload-browse btn btn-gradient-primary btn-click1" type="button">Upload</button>
									</span>
								</div>

							</div>
						</div>
					</div>
				</div>

				<div class="form-group row">
					<div class="col-sm-4"></div>
					<div class="col-sm-8">
						<div class="col-md-offset-2 col-md-12 text-right">
							<input type="submit" value="Create" class="btn btn-gradient-primary btn-rounded btn-fw" />
						</div>
					</div>
				</div>

			}
		</div>
	</div>
	<script src="https://code.jquery.com/jquery-3.3.1.js" type="text/javascript"></script>
	<script src="~/Assets/vendors/js/vendor.bundle.base.js"></script>
	<script src="~/Assets/vendors/js/vendor.bundle.addons.js"></script>
	<script src="~/Assets/js/off-canvas.js"></script>
	<script src="~/Assets/js/misc.js"></script>
	<script src="~/Assets/js/dashboard.js"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" type="text/javascript"></script>
	<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js" type="text/javascript"></script>
	<script src="~/Assets/datatable/Responsive-2.2.2/js/dataTables.responsive.min.js"></script>
	<script src="~/Assets/datatable/FixedHeader-3.1.4/js/dataTables.fixedHeader.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
	<script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
	@RenderSection("ClientScript", false)
	<script>
		function loader() {
			$("#loading").fadeOut(1000);
		};
		function showDialogLich() {
			$('#model-lich').modal({
				showClose: false,
				fadeDuration: 200,
			});
		}

		$(".btn-click1").click(function () {
			$(".file-click").click();

			$('.file-click[type="file"]').change(function (e) {
				var fileName = e.target.files[0].name;
				$(".name-input").val(fileName);
				console.log(fileName);
			});
		});
	</script>
	<style>
		.btn-capnhaplichmon {
			padding-left: 25px;
			font-size: 16px;
			font-family: sans-serif;
			font-weight: 600;
		}
	</style>
</body>

</html>